name: Build Kotlin/Native
on: [ push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # https://kotlinlang.org/docs/native-target-support.html ; KonanTarget.name
        konan-target: [
          linux_x64, # Tier 1 ; native host
          macos_arm64, # Tier 1 ; native host
          macos_x64, # Tier 1 ; native host
          mingw_x64, # Tier 3 ; native host
        ]
        include:
          - konan-target: linux_x64 # Tier 1 ; native host
            os: ubuntu-latest
          - konan-target: macos_arm64 # Tier 1 ; native host
            os: macos-latest
          - konan-target: macos_x64 # Tier 1 ; native host
            os: macos-latest
          - konan-target: mingw_x64 # Tier 3 ; native host
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle 7.5
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build for Kotlin/Native
        run: gradle -D konan.target=${{ matrix.konan-target }} nativeMainKlibrary

      - name: Test for Kotlin/Native
        run: gradle -D konan.target=${{ matrix.konan-target }} nativeTest
